### ISSUE TITLE
make custom-caffe error

### ISSUE THREAD

**Issue by liguiyuan** [goodluckcwl/Face-alignment-mobilenet-v2#13]
Hi, thinks for you open source, I have a problem on installed custom-caffe, can you tell me how to solve it, thanks!

`src/caffe/layers/visual_layer.cpp: In member function ‘virtual void caffe::VisualLayer<Dtype>::Forward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
src/caffe/layers/visual_layer.cpp:78:12: error: ‘imwrite’ is not a member of ‘cv’
         if(cv::imwrite(filename, cv_img)){
            ^
Makefile:582: recipe for target '.build_release/src/caffe/layers/visual_layer.o' failed
make: *** [.build_release/src/caffe/layers/visual_layer.o] Error 1
make: *** 正在等待未完成的任务....
`

**Comment by goodluckcwl** [comment]
Sorry. Please add 
#include <opencv2/opencv.hpp>
to the visual_layer.cpp
